name: Release RealCheck Monitor

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/monitor/package-lock.json

      - name: Install dependencies
        run: |
          cd apps/monitor
          npm ci

      - name: Build application
        run: |
          cd apps/monitor
          npm run build

      - name: Build installer
        run: |
          cd apps/monitor
          if [ "$RUNNER_OS" = "Windows" ]; then
            npm run dist:win
          elif [ "$RUNNER_OS" = "macOS" ]; then
            npm run dist:mac
          else
            npm run dist:linux
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: realcheck-monitor-${{ runner.os }}
          path: apps/monitor/dist-installers/

  create-release:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/realcheck-monitor-ubuntu-latest/*
            artifacts/realcheck-monitor-windows-latest/*
            artifacts/realcheck-monitor-macOS-latest/*
          body: |
            ## RealCheck Monitor v${{ github.ref_name }}
            
            ### What's New
            - AI-powered monitoring for interviews and assessments
            - Real-time behavior detection
            - Cross-platform support (Windows, macOS, Linux)
            - Secure authentication with Supabase
            
            ### Installation
            1. Download the appropriate installer for your platform
            2. Run the installer
            3. Launch RealCheck Monitor
            4. Sign in with your credentials
            
            ### Supported Platforms
            - **Windows**: Windows 10/11 (64-bit)
            - **macOS**: macOS 10.15 or later
            - **Linux**: Ubuntu 18.04+ (AppImage)
            
            ### Security
            RealCheck Monitor is designed with privacy and security in mind. The app only monitors for AI tools and suspicious behavior during authorized sessions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 